### ISSUE TITLE
Model fitting for different distributions

### ISSUE THREAD

**Issue by Vittoriayang** [Linbin-Lai/DAS-Group-01#2]
I have tried using Poisson model, but the AIC is very big. Can I try using binomial?

**Comment by Linbin-Lai** [comment]
Thanks for your question, I have added this part based on your suggestion and will update it later.

**Comment by Linbin-Lai** [comment]
Because I'm processes a count response variable. And in many cases, their distribution is not normally distributed. Usually use Poisson regression.
